title: Your awesome title
email: your-email@example.com
description: "A space for community to share and grow individual and collective capacities for societal change"

baseurl: "/abc-hub"
url: "https://architecture-beyond-capitalism.github.io"
github_username: architecture-beyond-capitalism

repository: "architecture-beyond-capitalism/abc-hub"

plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - github-pages
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: expanded
#  destination: ./site

autoprefixer:
  browsers:
    - last 4 versions
#    - Safari > 2

collections:
  profiles:
    output: true
    label: "Profiles"
  resources:
    output: true
    label: "Resource"
  posts:
    output: true
    label: "Post"
  ideas:
    output: true
    label: "Ideas"
